alias: COSMO
description: ""
triggers:
  - trigger: webhook
    allowed_methods:
      - POST
      - PUT
      - GET
    local_only: true
    webhook_id: cosmo
conditions: []
actions:
  - target:
      entity_id:
        - notify.cosmo_speak
    data:
      message: >-
        Hi Richard,  {{ trigger.json.voice | regex_replace(find='[^\w\s,.!?]',
        replace='')  }}
    action: notify.send_message
    enabled: true
  - action: system_log.write
    data:
      level: warning
      message: COSMO speech: {{ trigger.json.voice  }}
mode: single
